name: 'Welcome NewQuery'
description: 'looking new query since the last run.'
author: 'pyama86'
inputs:
  save_path:
    description: 'result file save path'
    required: false
    default: '/new_queries'
runs:
  using: 'docker'
  image: 'docker://pyama86/welcome-new-queries:latest'
  outputs:
    new_queries:
      descriptions: 'difference queries'
  args:
    - '${{ inputs.save_path}}'
branding:
  icon: 'search'
  color: 'green'
