version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log-output=TABLE --general-log
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
    - 3306:3306
  workload:
    image: mysql:5.7
    environment:
      TZ: 'Asia/Tokyo'
    command: [
      "mysqlslap",
      "--iterations=2",
      "--number-int-cols=4",
      "--number-char-cols=4",
      "--user=root",
      "--host=db",
      "--engine=innodb",
      "--auto-generate-sql",
      "--number-of-queries=1000",
      "--auto-generate-sql-load-type=read",
    ]
    external_links:
      - db
    depends_on:
      - db
  parser:
    build: ./analysis/
    volumes:
      - ./analysis:/opt/dev
    environment:
      TZ: 'Asia/Tokyo'
    external_links:
      - db
    depends_on:
      - workload
    command: ["db", "root", "", "/opt/dev/result"]
