name: 'Enable QueryLog'
description: 'switch on query.log.'
author: 'pyama86'
inputs:
  db_host:
    description: 'db hosname'
    required: true
  db_user:
    description: 'db user'
    required: false
    default: 'root'
  db_password:
    description: 'db password'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://pyama/enable-querylog:latest'
branding:
  icon: 'log-out'
  color: 'green'
