name: 'Welcome NewQuery'
description: 'looking new query since the last run.'
author: 'pyama86'
inputs:
  save-path:
    description: 'result file save path'
    required: false
    default: '/new_queries'
outputs:
  new_queries:
    description: 'difference queries'
  save-path:
    description: 'result file save path'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.save-path}}'
branding:
  icon: 'search'
  color: 'green'
