name: Publish Docker image
on:
  push:
    branches:
      - default
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Enable QueryLog Image Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pyama/enable-querylog:latest
          context: ./enable-querylog
      - name: Analysis Image Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pyama/query-analysis:latest
          context: ./analysis
