name: Test

on:
  pull_request:

jobs:
  test:
    name: Self Action Test
    strategy:
      matrix:
        #version: [5.6, 5.7, 8]
        version: [5.6]
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: db
      MYSQL_USER: root
    steps:
      - run: sudo apt update -qqy && sudo apt install -qqy mysql-client
      - uses: actions/checkout@v2
      - run: mysql -h 127.0.0.1 -u root -D mysql -sse "select 1"
      - uses: ./enable-querylog
      - name: Runs benchmark
        run: |
          mysqlslap \
          --iterations=2 \
          --number-int-cols=4 \
          --number-char-cols=4 \
          --user=root \
          --host=127.0.0.1 \
          --engine=innodb \
          --auto-generate-sql \
          --number-of-queries=1000 \
          --auto-generate-sql-load-type=read
      - name: Runs looking new query
        uses: ./analysis
        with:
          save-path: /tmp/new_queries
    services:
      db:
        image: mysql:${{ matrix.version}}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
