name: Test

on:
  pull_request:

jobs:
  test:
    name: Self Action Test
    strategy:
      matrix:
        version: [5.6, 5.7, 8]
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update -qqy && sudo apt install -qqy mysql-client
      - uses: actions/checkout@v2
      - uses: pyama86/enable-querylog@v0.1.0
      - name: Runs benchmark
        run: |
          mysqlslap \
          --iterations=2 \
          --number-int-cols=4 \
          --number-char-cols=4 \
          --user=root \
          --host=db \
          --password=root \
          --engine=innodb \
          --auto-generate-sql \
          --number-of-queries=1000 \
          --auto-generate-sql-load-type=read

      - name: Runs looking new query
        uses: ./
        with:
          save-path: /tmp/new_queries
    services:
      db:
        image: mysql:${{ matrix.version}}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
